server:
  port: 8082
  servlet:
    context-path: '/ead-course/' # path da rota do gateway

spring:
  application:
    name: ead-course-service
  config:
    import: 'optional:configserver:' # usa o configserver e se ele nao estiver disponivel usa as configs locais
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
  #  configuracao do banco
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course-async
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update  # cria as tabelas automaticamente no banco
      dialect: org.hibernate.dialect.PostgreSQLDialect  # dialeto do postgres
      jdbc:
        lob.non-contextual-creation: true # evita logs de erro (devido consultas do hibernate a metadados do banco)
    properties:
      hibernate:
        show_sql: true # mostra as consultas no log
  rabbitmq:
    addresses: amqps://jgsmgoyt:B2MgZ72W7S3HQlXeN0DnSDj3dIPAWokP@moose.rmq.cloudamqp.com/jgsmgoyt

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser' # nome do servico de authuser e o seu context path
  broker:
    exchange:
      userEventExchange: ead.userevent
      notificationCommandExchange: ead.notificationcommand
    queue:
      userEventQueue:
        name: ead.userevent.ms.course
    key:
      notificationCommandKey: ms.notification

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka' # endereco onde o eureka esta disponivel
  instance:
    hostname: localhost # para se registrar utilizando host
